// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnU9CAgPs8w3V4jlRpW_iLNcoAEypboY',
    appId: '1:573875158911:web:a893420cc325aebd53244a',
    messagingSenderId: '573875158911',
    projectId: 'smartwastemanagementsyst-da183',
    authDomain: 'smartwastemanagementsyst-da183.firebaseapp.com',
    storageBucket: 'smartwastemanagementsyst-da183.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8mHL3U9t8gHrX6Zo07y7Esozd7VOUbyg',
    appId: '1:573875158911:android:c3f2d22d41efbfdf53244a',
    messagingSenderId: '573875158911',
    projectId: 'smartwastemanagementsyst-da183',
    storageBucket: 'smartwastemanagementsyst-da183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWpfFx36PGn-v_3QyG_jdbgixjGgGRkM',
    appId: '1:573875158911:ios:50aafb3feb44fc5b53244a',
    messagingSenderId: '573875158911',
    projectId: 'smartwastemanagementsyst-da183',
    storageBucket: 'smartwastemanagementsyst-da183.appspot.com',
    iosClientId: '573875158911-avum6npblpot9v7g98uroqcn144smol4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWasteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWpfFx36PGn-v_3QyG_jdbgixjGgGRkM',
    appId: '1:573875158911:ios:caa3576727fa48f153244a',
    messagingSenderId: '573875158911',
    projectId: 'smartwastemanagementsyst-da183',
    storageBucket: 'smartwastemanagementsyst-da183.appspot.com',
    iosClientId: '573875158911-4kkteo5qrf7dg44a1bmc82d0bt6j1bcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWasteManagement.RunnerTests',
  );
}
